# Generated by Django 5.2.8 on 2025-11-17 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('REPUESTO', 'Repuesto'), ('ACCESORIO', 'Accesorio'), ('PERIFERICO', 'Periférico'), ('INSUMO', 'Insumo Taller')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False)),
                ('cantDisponible', models.IntegerField(default=0)),
                ('stockMinimo', models.IntegerField(default=5)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.producto')),
            ],
        ),
    ]
