# Generated by Django 5.2.8 on 2025-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ordencompra_detalleorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='presupuestoAdjunto',
            field=models.FileField(blank=True, null=True, upload_to='presupuestos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
