# Generated by Django 5.2.8 on 2025-11-17 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('idDiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionFalla', models.TextField()),
                ('fechaDiagnostico', models.DateTimeField(auto_now_add=True)),
                ('costoDiagnostico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('idDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numeroSerie', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.URLField(blank=True, max_length=255, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('idReparacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('Esperando Diagnostico', 'Esperando Diagnóstico'), ('Esperando Respuesta del Cliente', 'Esperando Respuesta del Cliente'), ('Esperando Insumos', 'Esperando Insumos'), ('En Reparacion', 'En Reparación'), ('Listo para Retirar', 'Listo para Retirar'), ('Retirado', 'Retirado'), ('Rechazado por el cliente', 'Rechazado por el cliente')], default='Esperando Diagnostico', max_length=100)),
                ('descCliente', models.TextField(blank=True, null=True)),
                ('codigoSec', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to=settings.AUTH_USER_MODEL)),
                ('diagnostico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reparaciones.diagnostico')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='reparaciones.dispositivo')),
                ('tecnicoAsignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
