# Generated by Django 5.2.8 on 2025-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos/'),
        ),
    ]
